### ISSUE TITLE
后台跑不起来，node18.x

### ISSUE THREAD

**Issue by Star945** [five6/ruoyi-pro-nestjs#2]
我重新弄了下依赖
更新到nest 10.x了
另外winston的写法也变了
redis那个插件也不支持10.x了
我上传个地址
https://github.com/Star945/ruoyi-nest-server

**Comment by five6** [comment]
强，支持一波

**Comment by Star945** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by five6** [comment]
强，支持一波

**Comment by Star945** [comment]
> 强，支持一波

我基本不会~全看你那个写法然后对照官方文档，然后还趟了个官方依赖冲突的坑，方便加个好友
